[package]
name = "bevy-example"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
transform-gizmo-bevy.workspace = true

bevy.workspace = true
bevy_mod_outline = "0.13.0"

[dependencies.bevy_egui]
git = "https://github.com/kisya-games/bevy_egui"
branch = "egui-0.36"
features = ["open_url", "default_fonts", "render"]
default-features = false

[lints]
workspace = true
